// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1SevvAUwEf3dMYbUYgicaKZknFoasUjA',
    appId: '1:509131998206:web:b0bfd613a6da9ce155b6af',
    messagingSenderId: '509131998206',
    projectId: 'sevaku-5dec7',
    authDomain: 'sevaku-5dec7.firebaseapp.com',
    storageBucket: 'sevaku-5dec7.firebasestorage.app',
    measurementId: 'G-PFPHKBK0NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBmYTjBDhqOaj-NjaHwb6MbGXnWdM_N2w',
    appId: '1:509131998206:android:717a394fde75fce855b6af',
    messagingSenderId: '509131998206',
    projectId: 'sevaku-5dec7',
    storageBucket: 'sevaku-5dec7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY469pvVoR237jSKW9x8_VGWOtZghX3WA',
    appId: '1:509131998206:ios:afb3f973281b1d4e55b6af',
    messagingSenderId: '509131998206',
    projectId: 'sevaku-5dec7',
    storageBucket: 'sevaku-5dec7.firebasestorage.app',
    iosClientId: '509131998206-fvjnn1f4re0edb766rom08cmk3a6fr5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.sevaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY469pvVoR237jSKW9x8_VGWOtZghX3WA',
    appId: '1:509131998206:ios:afb3f973281b1d4e55b6af',
    messagingSenderId: '509131998206',
    projectId: 'sevaku-5dec7',
    storageBucket: 'sevaku-5dec7.firebasestorage.app',
    iosClientId: '509131998206-fvjnn1f4re0edb766rom08cmk3a6fr5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.sevaku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1SevvAUwEf3dMYbUYgicaKZknFoasUjA',
    appId: '1:509131998206:web:bd1606d900eec01c55b6af',
    messagingSenderId: '509131998206',
    projectId: 'sevaku-5dec7',
    authDomain: 'sevaku-5dec7.firebaseapp.com',
    storageBucket: 'sevaku-5dec7.firebasestorage.app',
    measurementId: 'G-XTGVQ0Z8SM',
  );
}
